# Generated by Django 2.2.6 on 2021-05-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tasks", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="TaskItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=250)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="task_items",
            field=models.ManyToManyField(to="tasks.TaskItem"),
        ),
    ]
